#include "translate.h"

#define IMAGE_TO_VK(item) \
	case IMAGE_##item: return VK_##item;

#define TO_VK(item) \
	case item: return VK_##item##_BIT;

#define ACCESS_TO_VK(item)\
	case RENDER_MODULE_##item: return VK_##item##_BIT;

VkImageAspectFlags translateImageAspect(ImageAspectFlags aspectFlags) {
	switch (aspectFlags) {
		TO_VK(IMAGE_ASPECT_COLOR);
		TO_VK(IMAGE_ASPECT_DEPTH);
		TO_VK(IMAGE_ASPECT_STENCIL);
	default: return VK_IMAGE_ASPECT_NONE;
	}
}

VkImageUsageFlags translateImageUsage(ImageUsageFlags imageUsage) {
	VkImageUsageFlags usage = 0;
	usage |= VK_IMAGE_USAGE_TRANSFER_SRC_BIT * ((imageUsage & IMAGE_USAGE_TRANSFER_SRC_BIT) > 0);
	usage |= VK_IMAGE_USAGE_TRANSFER_DST_BIT & ((imageUsage & IMAGE_USAGE_TRANSFER_DST_BIT) > 0);
	usage |= VK_IMAGE_USAGE_SAMPLED_BIT * ((imageUsage & IMAGE_USAGE_SAMPLED_BIT) > 0);
	usage |= VK_IMAGE_USAGE_STORAGE_BIT * ((imageUsage & IMAGE_USAGE_STORAGE_BIT) > 0);
	usage |= VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT * ((imageUsage & IMAGE_USAGE_COLOR_ATTACHMENT_BIT) > 0);
	usage |= VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT * ((imageUsage & IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT) > 0);
	usage |= VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT * ((imageUsage & IMAGE_USAGE_INPUT_ATTACHMENT_BIT) > 0);
	usage |= VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT * ((imageUsage & IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT) > 0);
	usage |= VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR * ((imageUsage & IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR) > 0);
	usage |= VK_IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI * ((imageUsage & IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI) > 0);
	usage |= VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV * ((imageUsage & IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV) > 0);
	return usage;
}

VkSampleCountFlags translateSampleCount(ImageSampleCount sampleCount) {
	switch (sampleCount) {
	case IMAGE_SAMPLE_COUNT_1: return VK_SAMPLE_COUNT_1_BIT;
	case IMAGE_SAMPLE_COUNT_2: return VK_SAMPLE_COUNT_2_BIT;
	case IMAGE_SAMPLE_COUNT_4: return VK_SAMPLE_COUNT_4_BIT;
	case IMAGE_SAMPLE_COUNT_8: return VK_SAMPLE_COUNT_8_BIT;
	case IMAGE_SAMPLE_COUNT_16: return VK_SAMPLE_COUNT_16_BIT;
	case IMAGE_SAMPLE_COUNT_32: return VK_SAMPLE_COUNT_32_BIT;
	case IMAGE_SAMPLE_COUNT_64: return VK_SAMPLE_COUNT_64_BIT;
	default: return VK_SAMPLE_COUNT_1_BIT;
	}
}

VkFormat translateImageFormat(ImageFormat format) {

	//translate all ImageFormat to VkFormat
	switch (format) {
		IMAGE_TO_VK(FORMAT_UNDEFINED);
		IMAGE_TO_VK(FORMAT_R4G4_UNORM_PACK8);
		IMAGE_TO_VK(FORMAT_R4G4B4A4_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_B4G4R4A4_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_R5G6B5_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_B5G6R5_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_R5G5B5A1_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_B5G5R5A1_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_A1R5G5B5_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_R8_UNORM);
		IMAGE_TO_VK(FORMAT_R8_SNORM);
		IMAGE_TO_VK(FORMAT_R8_USCALED);
		IMAGE_TO_VK(FORMAT_R8_SSCALED);
		IMAGE_TO_VK(FORMAT_R8_UINT);
		IMAGE_TO_VK(FORMAT_R8_SINT);
		IMAGE_TO_VK(FORMAT_R8_SRGB);
		IMAGE_TO_VK(FORMAT_R8G8_UNORM);
		IMAGE_TO_VK(FORMAT_R8G8_SNORM);
		IMAGE_TO_VK(FORMAT_R8G8_USCALED);
		IMAGE_TO_VK(FORMAT_R8G8_SSCALED);
		IMAGE_TO_VK(FORMAT_R8G8_UINT);
		IMAGE_TO_VK(FORMAT_R8G8_SINT);
		IMAGE_TO_VK(FORMAT_R8G8_SRGB);
		IMAGE_TO_VK(FORMAT_R8G8B8_UNORM);
		IMAGE_TO_VK(FORMAT_R8G8B8_SNORM);
		IMAGE_TO_VK(FORMAT_R8G8B8_USCALED);
		IMAGE_TO_VK(FORMAT_R8G8B8_SSCALED);
		IMAGE_TO_VK(FORMAT_R8G8B8_UINT);
		IMAGE_TO_VK(FORMAT_R8G8B8_SINT);
		IMAGE_TO_VK(FORMAT_R8G8B8_SRGB);
		IMAGE_TO_VK(FORMAT_B8G8R8_UNORM);
		IMAGE_TO_VK(FORMAT_B8G8R8_SNORM);
		IMAGE_TO_VK(FORMAT_B8G8R8_USCALED);
		IMAGE_TO_VK(FORMAT_B8G8R8_SSCALED);
		IMAGE_TO_VK(FORMAT_B8G8R8_UINT);
		IMAGE_TO_VK(FORMAT_B8G8R8_SINT);
		IMAGE_TO_VK(FORMAT_B8G8R8_SRGB);
		IMAGE_TO_VK(FORMAT_R8G8B8A8_UNORM);
		IMAGE_TO_VK(FORMAT_R8G8B8A8_SNORM);
		IMAGE_TO_VK(FORMAT_R8G8B8A8_USCALED);
		IMAGE_TO_VK(FORMAT_R8G8B8A8_SSCALED);
		IMAGE_TO_VK(FORMAT_R8G8B8A8_UINT);
		IMAGE_TO_VK(FORMAT_R8G8B8A8_SINT);
		IMAGE_TO_VK(FORMAT_R8G8B8A8_SRGB);
		IMAGE_TO_VK(FORMAT_B8G8R8A8_UNORM);
		IMAGE_TO_VK(FORMAT_B8G8R8A8_SNORM);
		IMAGE_TO_VK(FORMAT_B8G8R8A8_USCALED);
		IMAGE_TO_VK(FORMAT_B8G8R8A8_SSCALED);
		IMAGE_TO_VK(FORMAT_B8G8R8A8_UINT);
		IMAGE_TO_VK(FORMAT_B8G8R8A8_SINT);
		IMAGE_TO_VK(FORMAT_B8G8R8A8_SRGB);
		IMAGE_TO_VK(FORMAT_A8B8G8R8_UNORM_PACK32);
		IMAGE_TO_VK(FORMAT_A8B8G8R8_SNORM_PACK32);
		IMAGE_TO_VK(FORMAT_A8B8G8R8_USCALED_PACK32);
		IMAGE_TO_VK(FORMAT_A8B8G8R8_SSCALED_PACK32);
		IMAGE_TO_VK(FORMAT_A8B8G8R8_UINT_PACK32);
		IMAGE_TO_VK(FORMAT_A8B8G8R8_SINT_PACK32);
		IMAGE_TO_VK(FORMAT_A8B8G8R8_SRGB_PACK32);
		IMAGE_TO_VK(FORMAT_A2R10G10B10_UNORM_PACK32);
		IMAGE_TO_VK(FORMAT_A2R10G10B10_SNORM_PACK32);
		IMAGE_TO_VK(FORMAT_A2R10G10B10_USCALED_PACK32);
		IMAGE_TO_VK(FORMAT_A2R10G10B10_SSCALED_PACK32);
		IMAGE_TO_VK(FORMAT_A2R10G10B10_UINT_PACK32);
		IMAGE_TO_VK(FORMAT_A2R10G10B10_SINT_PACK32);
		IMAGE_TO_VK(FORMAT_A2B10G10R10_UNORM_PACK32);
		IMAGE_TO_VK(FORMAT_A2B10G10R10_SNORM_PACK32);
		IMAGE_TO_VK(FORMAT_A2B10G10R10_USCALED_PACK32);
		IMAGE_TO_VK(FORMAT_A2B10G10R10_SSCALED_PACK32);
		IMAGE_TO_VK(FORMAT_A2B10G10R10_UINT_PACK32);
		IMAGE_TO_VK(FORMAT_A2B10G10R10_SINT_PACK32);
		IMAGE_TO_VK(FORMAT_R16_UNORM);
		IMAGE_TO_VK(FORMAT_R16_SNORM);
		IMAGE_TO_VK(FORMAT_R16_USCALED);
		IMAGE_TO_VK(FORMAT_R16_SSCALED);
		IMAGE_TO_VK(FORMAT_R16_UINT);
		IMAGE_TO_VK(FORMAT_R16_SINT);
		IMAGE_TO_VK(FORMAT_R16_SFLOAT);
		IMAGE_TO_VK(FORMAT_R16G16_UNORM);
		IMAGE_TO_VK(FORMAT_R16G16_SNORM);
		IMAGE_TO_VK(FORMAT_R16G16_USCALED);
		IMAGE_TO_VK(FORMAT_R16G16_SSCALED);
		IMAGE_TO_VK(FORMAT_R16G16_UINT);
		IMAGE_TO_VK(FORMAT_R16G16_SINT);
		IMAGE_TO_VK(FORMAT_R16G16_SFLOAT);
		IMAGE_TO_VK(FORMAT_R16G16B16_UNORM);
		IMAGE_TO_VK(FORMAT_R16G16B16_SNORM);
		IMAGE_TO_VK(FORMAT_R16G16B16_USCALED);
		IMAGE_TO_VK(FORMAT_R16G16B16_SSCALED);
		IMAGE_TO_VK(FORMAT_R16G16B16_UINT);
		IMAGE_TO_VK(FORMAT_R16G16B16_SINT);
		IMAGE_TO_VK(FORMAT_R16G16B16_SFLOAT);
		IMAGE_TO_VK(FORMAT_R16G16B16A16_UNORM);
		IMAGE_TO_VK(FORMAT_R16G16B16A16_SNORM);
		IMAGE_TO_VK(FORMAT_R16G16B16A16_USCALED);
		IMAGE_TO_VK(FORMAT_R16G16B16A16_SSCALED);
		IMAGE_TO_VK(FORMAT_R16G16B16A16_UINT);
		IMAGE_TO_VK(FORMAT_R16G16B16A16_SINT);
		IMAGE_TO_VK(FORMAT_R16G16B16A16_SFLOAT);
		IMAGE_TO_VK(FORMAT_R32_UINT);
		IMAGE_TO_VK(FORMAT_R32_SINT);
		IMAGE_TO_VK(FORMAT_R32_SFLOAT);
		IMAGE_TO_VK(FORMAT_R32G32_UINT);
		IMAGE_TO_VK(FORMAT_R32G32_SINT);
		IMAGE_TO_VK(FORMAT_R32G32_SFLOAT);
		IMAGE_TO_VK(FORMAT_R32G32B32_UINT);
		IMAGE_TO_VK(FORMAT_R32G32B32_SINT);
		IMAGE_TO_VK(FORMAT_R32G32B32_SFLOAT);
		IMAGE_TO_VK(FORMAT_R32G32B32A32_UINT);
		IMAGE_TO_VK(FORMAT_R32G32B32A32_SINT);
		IMAGE_TO_VK(FORMAT_R32G32B32A32_SFLOAT);
		IMAGE_TO_VK(FORMAT_R64_UINT);
		IMAGE_TO_VK(FORMAT_R64_SINT);
		IMAGE_TO_VK(FORMAT_R64_SFLOAT);
		IMAGE_TO_VK(FORMAT_R64G64_UINT);
		IMAGE_TO_VK(FORMAT_R64G64_SINT);
		IMAGE_TO_VK(FORMAT_R64G64_SFLOAT);
		IMAGE_TO_VK(FORMAT_R64G64B64_UINT);
		IMAGE_TO_VK(FORMAT_R64G64B64_SINT);
		IMAGE_TO_VK(FORMAT_R64G64B64_SFLOAT);
		IMAGE_TO_VK(FORMAT_R64G64B64A64_UINT);
		IMAGE_TO_VK(FORMAT_R64G64B64A64_SINT);
		IMAGE_TO_VK(FORMAT_R64G64B64A64_SFLOAT);
		IMAGE_TO_VK(FORMAT_B10G11R11_UFLOAT_PACK32);
		IMAGE_TO_VK(FORMAT_E5B9G9R9_UFLOAT_PACK32);
		IMAGE_TO_VK(FORMAT_D16_UNORM);
		IMAGE_TO_VK(FORMAT_X8_D24_UNORM_PACK32);
		IMAGE_TO_VK(FORMAT_D32_SFLOAT);
		IMAGE_TO_VK(FORMAT_S8_UINT);
		IMAGE_TO_VK(FORMAT_D16_UNORM_S8_UINT);
		IMAGE_TO_VK(FORMAT_D24_UNORM_S8_UINT);
		IMAGE_TO_VK(FORMAT_D32_SFLOAT_S8_UINT);
		IMAGE_TO_VK(FORMAT_BC1_RGB_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC1_RGB_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_BC1_RGBA_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC1_RGBA_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_BC2_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC2_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_BC3_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC3_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_BC4_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC4_SNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC5_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC5_SNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC6H_UFLOAT_BLOCK);
		IMAGE_TO_VK(FORMAT_BC6H_SFLOAT_BLOCK);
		IMAGE_TO_VK(FORMAT_BC7_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_BC7_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ETC2_R8G8B8_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ETC2_R8G8B8_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_EAC_R11_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_EAC_R11_SNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_EAC_R11G11_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_EAC_R11G11_SNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_4x4_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_4x4_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_5x4_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_5x4_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_5x5_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_5x5_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_6x5_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_6x5_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_6x6_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_6x6_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_8x5_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_8x5_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_8x6_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_8x6_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_8x8_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_8x8_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x5_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x5_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x6_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x6_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x8_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x8_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x10_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_10x10_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_12x10_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_12x10_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_12x12_UNORM_BLOCK);
		IMAGE_TO_VK(FORMAT_ASTC_12x12_SRGB_BLOCK);
		IMAGE_TO_VK(FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG);
		IMAGE_TO_VK(FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT);
		IMAGE_TO_VK(FORMAT_G8B8G8R8_422_UNORM);
		IMAGE_TO_VK(FORMAT_B8G8R8G8_422_UNORM);
		IMAGE_TO_VK(FORMAT_G8_B8_R8_3PLANE_420_UNORM);
		IMAGE_TO_VK(FORMAT_G8_B8R8_2PLANE_420_UNORM);
		IMAGE_TO_VK(FORMAT_G8_B8_R8_3PLANE_422_UNORM);
		IMAGE_TO_VK(FORMAT_G8_B8R8_2PLANE_422_UNORM);
		IMAGE_TO_VK(FORMAT_G8_B8_R8_3PLANE_444_UNORM);
		IMAGE_TO_VK(FORMAT_R10X6_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_R10X6G10X6_UNORM_2PACK16);
		IMAGE_TO_VK(FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16);
		IMAGE_TO_VK(FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16);
		IMAGE_TO_VK(FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16);
		IMAGE_TO_VK(FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_R12X4_UNORM_PACK16);
		IMAGE_TO_VK(FORMAT_R12X4G12X4_UNORM_2PACK16);
		IMAGE_TO_VK(FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16);
		IMAGE_TO_VK(FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16);
		IMAGE_TO_VK(FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16);
		IMAGE_TO_VK(FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16);
		IMAGE_TO_VK(FORMAT_G16B16G16R16_422_UNORM);
		IMAGE_TO_VK(FORMAT_B16G16R16G16_422_UNORM);
		IMAGE_TO_VK(FORMAT_G16_B16_R16_3PLANE_420_UNORM);
		IMAGE_TO_VK(FORMAT_G16_B16R16_2PLANE_420_UNORM);
		IMAGE_TO_VK(FORMAT_G16_B16_R16_3PLANE_422_UNORM);
		IMAGE_TO_VK(FORMAT_G16_B16R16_2PLANE_422_UNORM);
		IMAGE_TO_VK(FORMAT_G16_B16_R16_3PLANE_444_UNORM);
		IMAGE_TO_VK(FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT);
		IMAGE_TO_VK(FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT);
		IMAGE_TO_VK(FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT);
		IMAGE_TO_VK(FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT);
		IMAGE_TO_VK(FORMAT_A4R4G4B4_UNORM_PACK16_EXT);
		IMAGE_TO_VK(FORMAT_A4B4G4R4_UNORM_PACK16_EXT);
	default:
		return VK_FORMAT_UNDEFINED;
	}
}

VkAccessFlags translateAccessFlags(RenderModuleAccessFlags access) {
	switch (access) {
		ACCESS_TO_VK(ACCESS_INDIRECT_COMMAND_READ);
		ACCESS_TO_VK(ACCESS_INDEX_READ);
		ACCESS_TO_VK(ACCESS_VERTEX_ATTRIBUTE_READ);
		ACCESS_TO_VK(ACCESS_UNIFORM_READ);
		ACCESS_TO_VK(ACCESS_INPUT_ATTACHMENT_READ);
		ACCESS_TO_VK(ACCESS_SHADER_READ);
		ACCESS_TO_VK(ACCESS_SHADER_WRITE);
		ACCESS_TO_VK(ACCESS_COLOR_ATTACHMENT_READ);
		ACCESS_TO_VK(ACCESS_COLOR_ATTACHMENT_WRITE);
		ACCESS_TO_VK(ACCESS_DEPTH_STENCIL_ATTACHMENT_READ);
		ACCESS_TO_VK(ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE);
		ACCESS_TO_VK(ACCESS_TRANSFER_READ);
		ACCESS_TO_VK(ACCESS_TRANSFER_WRITE);
		ACCESS_TO_VK(ACCESS_HOST_READ);
		ACCESS_TO_VK(ACCESS_HOST_WRITE);
		ACCESS_TO_VK(ACCESS_MEMORY_READ);
		ACCESS_TO_VK(ACCESS_MEMORY_WRITE);
	}
	return 0;
}

/*
	case IMAGE_FORMAT_UNDEFINED:
	return VK_FORMAT_UNDEFINED;
case IMAGE_FORMAT_R4G4_UNORM_PACK8:
	return VK_FORMAT_R4G4_UNORM_PACK8;
case IMAGE_FORMAT_R4G4B4A4_UNORM_PACK16:
	return VK_FORMAT_R4G4B4A4_UNORM_PACK16;
case IMAGE_FORMAT_B4G4R4A4_UNORM_PACK16:
	return VK_FORMAT_B4G4R4A4_UNORM_PACK16;
case IMAGE_FORMAT_R5G6B5_UNORM_PACK16:
	return VK_FORMAT_R5G6B5_UNORM_PACK16;
case IMAGE_FORMAT_B5G6R5_UNORM_PACK16:
	return VK_FORMAT_B5G6R5_UNORM_PACK16;
case IMAGE_FORMAT_R5G5B5A1_UNORM_PACK16:
	return VK_FORMAT_R5G5B5A1_UNORM_PACK16;
case IMAGE_FORMAT_B5G5R5A1_UNORM_PACK16:
	return VK_FORMAT_B5G5R5A1_UNORM_PACK16;
case IMAGE_FORMAT_A1R5G5B5_UNORM_PACK16:
	return VK_FORMAT_A1R5G5B5_UNORM_PACK16;
case IMAGE_FORMAT_R8_UNORM:
	return VK_FORMAT_R8_UNORM;
case IMAGE_FORMAT_R8_SNORM:
	return VK_FORMAT_R8_SNORM;
case IMAGE_FORMAT_R8_USCALED:
	return VK_FORMAT_R8_USCALED;
case IMAGE_FORMAT_R8_SSCALED:
	return VK_FORMAT_R8_SSCALED;
case IMAGE_FORMAT_R8_UINT:
	return VK_FORMAT_R8_UINT;
case IMAGE_FORMAT_R8_SINT:
	return VK_FORMAT_R8_SINT;
case IMAGE_FORMAT_R8_SRGB:
	return VK_FORMAT_R8_SRGB;
case IMAGE_FORMAT_R8G8_UNORM:
	return VK_FORMAT_R8G8_UNORM;
case IMAGE_FORMAT_R8G8_SNORM:
	return VK_FORMAT_R8G8_SNORM;
case IMAGE_FORMAT_R8G8_USCALED:
	return VK_FORMAT_R8G8_USCALED;
case IMAGE_FORMAT_R8G8_SSCALED:
	return VK_FORMAT_R8G8_SSCALED;
case IMAGE_FORMAT_R8G8_UINT:
	return VK_FORMAT_R8G8_UINT;
case IMAGE_FORMAT_R8G8_SINT:
	return VK_FORMAT_R8G8_SINT;
case IMAGE_FORMAT_R8G8_SRGB:
	return VK_FORMAT_R8G8_SRGB;
case IMAGE_FORMAT_R8G8B8_UNORM:
	return VK_FORMAT_R8G8B8_UNORM;
case IMAGE_FORMAT_R8G8B8_SNORM:
	return VK_FORMAT_R8G8B8_SNORM;
case IMAGE_FORMAT_R8G8B8_USCALED:
	return VK_FORMAT_R8G8B8_USCALED;
case IMAGE_FORMAT_R8G8B8_SSCALED:
	return VK_FORMAT_R8G8B8_SSCALED;
case IMAGE_FORMAT_R8G8B8_UINT:
	return VK_FORMAT_R8G8B8_UINT;
case IMAGE_FORMAT_R8G8B8_SINT:
	return VK_FORMAT_R8G8B8_SINT;
case IMAGE_FORMAT_R8G8B8_SRGB:
	return VK_FORMAT_R8G8B8_SRGB;
case IMAGE_FORMAT_B8G8R8_UNORM:
	return VK_FORMAT_B8G8R8_UNORM;
case IMAGE_FORMAT_B8G8R8_SNORM:
	return VK_FORMAT_B8G8R8_SNORM;
case IMAGE_FORMAT_B8G8R8_USCALED:
	return VK_FORMAT_B8G8R8_USCALED;
case IMAGE_FORMAT_B8G8R8_SSCALED:
	return VK_FORMAT_B8G8R8_SSCALED;
case IMAGE_FORMAT_B8G8R8_UINT:

*/

